version: '3.8'

services:
  svg-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app
      - /home/app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - redis
    networks:
      - svg-ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - svg-ai-network

volumes:
  redis_data:

networks:
  svg-ai-network:
    driver: bridge