apiVersion: v1
kind: Namespace
metadata:
  name: svg-ai-prod
  labels:
    app: svg-ai
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: svg-ai-quota
  namespace: svg-ai-prod
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"