apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-cache-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: api
    type: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: api
    type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-models-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: worker
    type: models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-cache-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: worker
    type: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-logs-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: worker
    type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage-pvc
  namespace: svg-ai-prod
  labels:
    app: svg-ai
    component: cache
    type: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-ssd